[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
    '@uma/core/contracts/=lib/protocol/packages/core/contracts/',
    'ds-test=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/'
]

[rpc_endpoints]
sepolia = "https://1rpc.io/sepolia"
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
